### ISSUE TITLE
Java Neo4j Harness, GDS

### ISSUE THREAD

**Issue by edern37** [neo4j/graph-data-science#360]
## Bug report

I try use neo4j 5.26.8 harness in Java 21 with GDS 2.13.4 but it doesn't work.

I there any solution ?

Thanks in advance for you work !

### Steps to reproduce
```
embeddedDatabaseServer =
        Neo4jBuilders.newInProcessBuilder()
            .withDisabledServer()
            .withConfig(GraphDatabaseSettings.plugin_dir, Paths.get("C:\\tests\\neo4jplugins"))
            .withConfig(GraphDatabaseSettings.procedure_unrestricted, List.of("apoc.*,gds.*"))
            .withConfig(GraphDatabaseSettings.logs_directory, Path.of("C:\\tests\\logs"))
```

My folder `C:\\tests\\neo4jplugins` have :
- apoc-core-5.26.8.jar
- neo4j-graph-data-science-2.13.4.jar

It work well just with the apoc jar.

It work well with docker `neo4j:5.26.8-community`

### Expected behavior
Server start with gds

### Actual behavior
Server doesn't start

```
2025-09-01 13:50:46.816+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.core.write.CypherNodePropertyExporterBuilder` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/kernel/enterprise/api/security/EnterpriseLoginContext
2025-09-01 13:50:47.051+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.io.netty.handler.codec.spdy.SpdyHeaderBlockJZlibEncoder` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/gds/shaded/com/jcraft/jzlib/Deflater
2025-09-01 13:50:47.219+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.io.netty.handler.codec.compression.LzfDecoder` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/gds/shaded/com/ning/compress/lzf/ChunkDecoder
2025-09-01 13:50:47.504+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.io.netty.handler.codec.marshalling.DefaultUnmarshallerProvider` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/gds/shaded/org/jboss/marshalling/Unmarshaller
2025-09-01 13:50:47.877+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.org.ejml.ops.MatrixIO$MflAccess$IO` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: us/hebi/matlab/mat/types/MatFile
2025-09-01 13:50:47.946+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.io.netty.handler.codec.protobuf.ProtobufEncoderNano` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/gds/shaded/com/google/protobuf/nano/MessageNano
2025-09-01 13:50:47.961+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `com.neo4j.gds.shaded.net.bytebuddy.dynamic.loading.ClassInjector$UsingJna$Dispatcher$Windows32BitFunctionMapper` from plugin jar `C:\tests\neo4jplugins\neo4j-graph-data-science-2.13.4.jar`: java.lang.NoClassDefFoundError: com/neo4j/gds/shaded/com/sun/jna/FunctionMapper
...
2025-09-01 13:50:59.567+0000 INFO  [o.n.d.d.DatabaseLifecycles] Stopping 'DatabaseId{00000000[system]}'.
```

**Comment by edern37** [comment]
Hello :) I'm not using any data, it's just starting the embedded neo4j server with the Graph Data Science plugin.
