### ISSUE TITLE
Open GDS 2.23.0 build fails at read.relationshipProperties expecting 4 instead of 5 parameters

### ISSUE THREAD

**Issue by JohT** [neo4j/graph-data-science#362]
**Describe the bug**

When trying to build open GDS 2.23.0 with Java 21.0.6 using the command `/gradlew -Dorg.gradle.logging.level=info "-Dorg.gradle.jvmargs=-Xmx2g" -Pneo4jVersion=2025.10.1 -- :open-packaging:shadowCopy`, the error message below is shown.

Reference pull request: https://github.com/JohT/open-graph-data-science-packaging/pull/91

```
Execution failed for task ':native-projection:compileJava'.
> Compilation failed; see the compiler output below.
  /home/runner/work/open-graph-data-science-packaging/open-graph-data-science-packaging/native-projection/src/main/java/org/neo4j/gds/projection/RelationshipsScannerTask.java:223: error: method relationshipProperties in interface Read cannot be applied to given types;
                          read.relationshipProperties(
                              ^
    required: long,Reference,PropertySelection,PropertyCursor
    found:    long,int,Reference,PropertySelection,PropertyCursor
    reason: actual and formal argument lists differ in length
  warning: Supported source version 'RELEASE_17' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '21'
  1 error
  1 warning
```

**To Reproduce**

GDS version:2.23.0
Neo4j version: 2025.10.1
Java version: Java 21.0.6+7.0.LTS (Temurin-Hotspot)
Operating system: Ubuntu 24.04.3 LTS

`/gradlew -Dorg.gradle.logging.level=info "-Dorg.gradle.jvmargs=-Xmx2g" -Pneo4jVersion=2025.10.1 -- :open-packaging:shadowCopy`

**Expected behavior**
Does work with GDS version 2.22.0 using the exact same settings.

**Additional context**
[full_log.txt](https://github.com/user-attachments/files/23779755/full_log.txt)

**Comment by JohT** [comment]
Thanks for your super fast reply. No worries. Waiting a couple of days is absolutely fine for me.

If I got you correctly @vnickolov, I can safely remove the `-Pneo4jVersion=2025.10.1` parameter, right?

**Comment by JohT** [comment]
Thanks for your help and explanation. I'll close this issue and wait for the next version.

**Comment by vnickolov** [comment]
Thank you @JohT, we will think about bringing the parameter back if it would be useful, any thoughts?

**Comment by JohT** [comment]
@vnickolov, here are my thoughts. I'm fine with any approach.

It could be valuable to get an early (fail-fast) validation if my expected Neo4j version (that I specified with the parameter) is incompatible with the version I'd like to build. 

If the plugin would most likely work with another Neo4j version and it's on my risk to use it (and maybe I get a warning), then it would also be nice to have the option to leave it out. This approach would then be practical but less clean (violating fail-fast) in my opinion.

That leads me to wonder why only one version of gds can be used with one version of the database. I can imagine that this leads to extra effort on your side and is a pity for some users that can't update Neo4j in the same pace as they would update gds. 

All in all I think that graph-data-science is incredible valuable and you all have assembled a amazing library!
